src/Entity/Booking.php
<?php

namespace App\Entity;

use App\Validator\NotAfternoon;
use App\Validator\NotClosed;
use App\Validator\NotFull;
use App\Validator\NotHoliday;
use App\Validator\NotSunday;
use App\Validator\NotTuesday;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 * @NotFull()
 * @NotAfternoon()
 * @NotClosed()
 *
 */
class Booking
{

    const MAX_NB_TICKETS = 10;
    const MIN_NB_TICKETS = 1;
    const NORMAL_DAY = 16;
    const SENIOR_DAY = 12;
    const FREE = 0;
    const CHILD_DAY = 8;
    const REDUCED_PRICE = 10;
    const TYPE_LABEL_DAY = "Journée";
    const TYPE_LABEL_HALF_DAY = "Demi-journée";
    const HALF_DAY_COEFF = 0.5;
    const TYPE_DAY = true;
    const TYPE_HALF_DAY = false;
    const NOT_AFTERNOON_HOUR = 14;
    const TOO_LATE_HOUR_DAY = "16:30";
    const TOO_LATE_HOUR_NIGHT = "20:00";
    const MAX_PER_DAY = 1000;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\GreaterThanOrEqual("today")
     * @NotTuesday()
     * @NotSunday()
     * @NotHoliday()
     */
    private $dateOfVisit;

    /**
     * @ORM\Column(type="boolean")
     */
    private $period;

    /**
     * @ORM\Column(type="integer")
     *
     */
    private $numberOfPeople;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;



    /**
     * @ORM\Column(type="integer")
     */
    private $price = 0;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ticket", mappedBy="booking", orphanRemoval=true, cascade={"persist"})
     * @Assert\Valid()
     */
    private $tickets;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $reference;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    public function __construct()
    {
        $this->tickets = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateOfVisit(): ?\DateTimeInterface
    {
        return $this->dateOfVisit;
    }

    public function setDateOfVisit(\DateTimeInterface $dateOfVisit): self
    {
        $this->dateOfVisit = $dateOfVisit;

        return $this;
    }

    public function getPeriod(): ?bool
    {
        return $this->period;
    }

    public function getPeriodLabel(): string
    {
        return $this->period ? self::TYPE_LABEL_DAY : self::TYPE_LABEL_HALF_DAY;
    }

    public function setPeriod(bool $period): self
    {
        $this->period = $period;

        return $this;
    }

    public function getNumberOfPeople(): ?int
    {
        return $this->numberOfPeople;
    }

    public function setNumberOfPeople(int $numberOfPeople): self
    {
        $this->numberOfPeople = $numberOfPeople;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }


    /**
     * @return Collection|Ticket[]
     */
    public function getTickets(): Collection
    {
        return $this->tickets;
    }

    public function addTicket(Ticket $ticket): self
    {

        if (!$this->tickets->contains($ticket)) {
            $this->tickets[] = $ticket;
            $ticket->setBooking($this);
        }

        return $this;
    }

    public function removeTicket(Ticket $ticket): self
    {
        if ($this->tickets->contains($ticket)) {
            $this->tickets->removeElement($ticket);
            // set the owning side to null (unless already changed)
            if ($ticket->getBooking() === $this) {
                $ticket->setBooking(null);
            }
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * @param mixed $price
     */
    public function setPrice($price)
    {
        $this->price = $price;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }




}

src/Form/BookingType.php
<?php

namespace App\Form;

use App\Entity\Booking;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BookingType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('dateOfVisit', DateType::class, [
                'label' => 'Date de visite',
                'widget' => 'single_text'
            ])
            ->add('period', ChoiceType::class, [
                'label' => 'Type de billet',
                'choices' => array(
                    Booking::TYPE_LABEL_DAY => Booking::TYPE_DAY,
                    Booking::TYPE_LABEL_HALF_DAY => Booking::TYPE_HALF_DAY,
                ),
                'expanded' => true,
            ])
            ->add('numberOfPeople', IntegerType::class, [
                'label' => 'Nombre de personne',
                'attr' => ['max' => Booking::MAX_NB_TICKETS,
                            'min' => Booking::MIN_NB_TICKETS]
            ])
            ->add('email', EmailType::class);

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Booking::class,
        ]);
    }
}

templates/booking/finish.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commander un billet{% endblock %}
{% block body %}
    <h2 class="pt-3">Votre commande a bien été enregistrée</h2>
    <section class="pt-3">
        <div class="card">
            <div class="card-body">
                <p class="text-sm-left">Merci pour votre commande, vous allez recevoir par courriel les éléments de votre commande
                    sur l'adresse que vous nous avez communiqué {{ booking.email }}.<br></p>

                <p class="text-sm-left">
                    Si vous ne recevez pas le courriel de confirmation contactez-nous par le moyen de votre choix courriel ou
                    téléphone et communiquez-nous la référence de votre commande <strong>{{ booking.reference }}</strong><br></p>
                <p class="text-sm-left"> - Contactez&nbsp;: <a href="mailto:assistance-billetterie@assistance.fr" rel="nofollow">assistance-billetterie@assistance.fr</a><br>
                    Tél. : +33 (0)1 00 10 20 30
                </p>
            </div>
        </div>



    </section>
{% endblock %}

templates/booking/payment.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commander un billet{% endblock %}

{% block body %}
    <div class="nav-space-checkout">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <h1 class="checkout-header">Finaliser votre commande</h1>
                </div>

                <div class="col-xs-12 col-sm-6">
                    <table class="table table-bordered">

                        <thead>
                        <tr>
                            <th class="col-xs-6 active">Nom Prénom</th>
                            <th class="col-xs-3 active text-center">Prix</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for ticket in booking.tickets %}
                            <tr>
                                <th class="col-xs-6 checkout-product-name">{{ ticket.name }} {{ ticket.firstName }}</th>
                                <td class="col-xs-3">${{ ticket.price }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                        <tfoot>
                        <tr>
                            <th class="col-xs-6 info">Total</th>
                            <td class="col-xs-3 info checkout-total">€{{ booking.price }}</td>
                        </tr>
                        </tfoot>
                    </table>
                </div>
                <div class="col-xs-12 col-sm-6">

                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/booking/step_one.html.twig
{% extends 'base.html.twig' %}


{% block title %}Commander un billet{% endblock %}
{% block body %}
    <h1 class="pt-3">Commander votre billet</h1>
    <div class="row no-gutters">
        <div class="col-md-8">
            <div class="form">
                <div class="step-one">
                    <span class="align-middle">
                        Etape 1/3
                    </span>

                </div>

                {{ form_start(form) }}
                <div class="pt-4">
                    {{ form_row(form.dateOfVisit) }}
                    <div class="radio">
                        {{ form_row(form.period) }}
                    </div>

                    {{ form_row(form.numberOfPeople) }}
                    {{ form_row(form.email) }}
                </div>

            <div class="booking-information">
                <p>
                    <span class="nbInfo">Le nombre de billets maximum par commande est de 10 </span>

                </p>
            </div>

            <button type="submit" class="btn btn-dark my-3">Valider</button>

            {{ form_end(form) }}
            </div>

        </div>

        {% include 'ticket/useful_information.html.twig' %}

    </div>

{% endblock %}

templates/booking/step_three.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commander un billet{% endblock %}
{% block body %}

<h1 class="pt-3">Récapitulatif de votre commande</h1>
    <div class="step-two">
        <span class="align-middle">
            Etape 3/3
        </span>
    </div>
<section class="pt-3">

    Vous avez commandé le(s) billet(s) suivant(s) :

    <p>Votre visite aura lieu le {{ booking.dateOfVisit| date('d-m-Y') }}
        et vos billets sont valables pour la {{ booking.periodLabel }}</p>

    <div class="table-responsive-sm">

        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col"></th>
                <th scope="col">Commande du</th>
                <th scope="col">Nom</th>
                <th scope="col">Prénom</th>
                <th scope="col">Date de naissance</th>
                <th scope="col">Email</th>
                <th scope="col">Pays</th>
                <th scope="col">Prix</th>
                <th scope="col">Réduction</th>
            </tr>
            </thead>
            <tbody>
            {% for ticket in booking.tickets %}
            <tr>
                <th scope="row">
                    {% for numberOfPeople in booking.numberOfPeople %}
                    {{ numberOfPeople }}
                    {% endfor %}</th>
                <td>{{ booking.createdAt|date('d-m-Y') }}</td>
                <td>{{ ticket.name }}</td>
                <td>{{ ticket.firstName }}</td>
                <td>{{ ticket.dateOfBirth|date('d-m-Y') }}</td>
                <td>{{ booking.email }}</td>
                <td>{{ ticket.country }}</td>
                <td>{{ ticket.price }}</td>
                <td> {% if ticket.reducedPrice == true %}
                        <p>Oui</p>
                        {% else %}
                        <p>Non</p>

                    {% endif %}</td>

            </tr>
            {% endfor %}
            <tr>

            </tbody>
        </table>

    </div>


    <div class="alert alert-success" role="alert">
        Le montant de votre commande s'élève à {{ booking.price }} €
    </div>


    <div class="col-4">
        <form action="" method="POST">
            <script
                    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                    data-key="pk_test_ZRJFa0Zmp708tIkrvO4pqUn400kwyrqAW3"
                    data-amount="{{ booking.price * 100 }}"
                    data-name="Billetterie du Louvre"
                    data-description="Projet 4"
                    data-email="{{ booking.email }}"
                    data-image="{{ asset('img/logo_Louvre.png') }}"
                    data-currency="EUR"
                    data-locale="auto">
            </script>
        </form>
    </div>
    <div class="col-md-4">
        <div class="go-back">
            <div id="order" class="row py-3">
                <a href="{{ path ('order_step_2') }}" class="btn btn-secondary btn-lg btn-block active" role="button"
                   aria-pressed="true">Revenir à l'étape précédente</a>
            </div>
        </div>
    </div>



</section>
{% endblock %}

templates/booking/step_two.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commander un billet{% endblock %}
{% block body %}
<div class="row no-gutters">
    <h1 class="pt-3">Commander votre billet</h1>
    <div class="col-md-8">
        <div class="form">
            <div class="step-two">
                <span class="align-middle">
                    Etape 2/3
                </span>
            </div>
                {{ form_start(form) }}
            <div class="pt-4">
                {% for formTicket in form.tickets %}
                    <h4>Billet n° {{ loop.index }}</h4>
                    {{ form_widget(formTicket) }}

                {% endfor %}
            </div>

        </div>

        <button type="submit" class="btn btn-dark">Valider</button>

        {{ form_end(form) }}
    </div>


    {% include 'ticket/useful_information.html.twig' %}

    <div class="col-md-4">
        <div class="go-back">
            <div id="order" class="row py-3">
                <a href="{{ path ('order_step_1') }}" class="btn btn-secondary btn-lg btn-block active" role="button"
                   aria-pressed="true">Revenir à l'étape précédente</a>
            </div>
        </div>
    </div>



</div>
{% endblock %}